### ISSUE TITLE
Implement 'registry delete-bucket' command

### ISSUE THREAD

**Issue by aperepel** [bbende/nifi#37]

**Comment by bbende** [comment]
This is obviously trivial to implement, however I didn't provide any delete commands because I was slightly concerned that someone would delete something accidentally and have no way of getting it back, so I was leaning towards forcing them to do more work to delete something (aka go into the UI and get a confirm delete prompt), thoughts?

**Comment by aperepel** [comment]
Yes, let's follow the `rm -f` behavior and prevent stupid mistakes, but not make deletion super difficult either. When I though about the quick import macro command, I expect it to create lots of flows in its bucket, which are quick and dirty and meant to try something out from a public domain quickly. Deleting those auto-imported flows would be a common operation.
